name: Deploy Website to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build and Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies & Build Project
        run: |
          npm ci
          npm run build
         env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}


      - name: Sync Output Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/          # Use ./build/ if using Create React App
          server-dir: ./    # Target directory on your hosting server